bmr:
  enabled: true
  max_generations: 100
  population_size: 40
bwr:
  enabled: true
  max_generations: 100
  population_size: 40
evaluation:
  batch_size: 16
  datasets:
  - name: vista-train
    path: /workspace/vista-data/train
    split: train
    weight: 0.6
  - name: vista-test
    path: /workspace/vista-data/test
    split: validation
    weight: 0.4
  metrics:
  - character_accuracy
  - field_extraction_accuracy
  - processing_speed
evolution:
  checkpoint:
    enabled: true
    interval: 5
    path: checkpoints
    save_population: true
    save_top_k: 5
  crossover_rate: 0.7
  elitism_count: 4
  fitness_weights:
    character_accuracy: 0.6
    field_extraction_accuracy: 0.3
    processing_speed: 0.1
  generations: 100
  mutation_rate: 0.2
  population_size: 40
  tournament_size: 5
field_extractor:
  params:
    batch_size: 32
    confidence_threshold: 0.7
    device: cuda
    model_name: cl-tohoku/bert-base-japanese-v2
    use_fp16: true
  target: evomerge.models.field_extractor.InvoiceFieldExtractor
model:
  params:
    confidence_threshold: 0.7
    device: cuda
    torch_dtype: float16
    tp_size: 2
    use_flash_attention: true
    use_tensor_parallel: true
  target: evomerge.models.japanese_ocr.JapaneseOCRModel
models:
  base_models:
  - local_path: models/stockmark-2-vl-100b-beta
    name: stockmark-2-vl-100b-beta
    repo_id: stockmark/stockmark-2-vl-100b-beta
    type: vlm
    weight_range:
    - 0.4
    - 0.8
  - local_path: models/vila-jp
    name: vila-jp
    repo_id: nlp-waseda/vila-jp
    type: vlm
    weight_range:
    - 0.3
    - 0.7
  - local_path: models/deepseek-vl2-small
    name: deepseek-vl2-small
    repo_id: deepseek-ai/deepseek-vl2-small
    type: vlm
    weight_range:
    - 0.2
    - 0.6
  - local_path: models/qwen2-5-vl-7b
    name: qwen2-5-vl-7b
    repo_id: Qwen/Qwen2-VL-7B
    type: vlm
    weight_range:
    - 0.1
    - 0.5
  - local_path: models/got-ocr2-0
    name: got-ocr2-0
    repo_id: microsoft/got-ocr2-0
    type: vlm
    weight_range:
    - 0.2
    - 0.5
  - local_path: models/shisa-gamma-7b-v1
    name: shisa-gamma-7b-v1
    repo_id: augmxnt/shisa-gamma-7b-v1
    type: llm
    weight_range:
    - 0.1
    - 0.3
  - local_path: models/elyza-japanese-ocr-7b
    name: elyza-japanese-ocr-7b
    repo_id: elyza/elyza-japanese-ocr-7b
    type: llm
    weight_range:
    - 0.3
    - 0.6
  - local_path: models/japanese-stablelm-7b
    name: japanese-stablelm-7b
    repo_id: stabilityai/japanese-stablelm-7b
    type: llm
    weight_range:
    - 0.2
    - 0.5
optimization:
  checkpoint_frequency: 5
  early_stopping:
    min_delta: 0.0005
    patience: 10
  max_generations: 100
  num_workers: 8
  parallel_evaluations: true
  population_size: 40
  seed: 42
visualization:
  enabled: true
  interactive: true
  plot_metrics:
  - character_accuracy
  - field_extraction_accuracy
  - processing_speed
  save_format: html
