model:
  target: evomerge.CausalLM
  params:
    model_path: elyza/elyza-japanese-ocr-7b
    template: ja-instruct
    model_kwargs:
      torch_dtype: torch.float16
    generation_config:
      max_new_tokens: 1024
      do_sample: false
      temperature: 0.1
      top_p: 0.95
      repetition_penalty: 1.3
      num_beams: 4
eval:
    - target: evomerge.eval.JaTextExtraction
      params:
        loader_kwargs:
          batch_size: 8
          num_workers: 2
    - target: evomerge.eval.JaFieldExtraction
      params:
        loader_kwargs:
          batch_size: 8
          num_workers: 2