model:
  target: evomerge.CausalLM
  params:
    model_path: rinna/japanese-document-llm-4b
    template: ja-instruct
    model_kwargs:
      torch_dtype: torch.float16
    generation_config:
      max_new_tokens: 512
      do_sample: false
      temperature: 0.3
      top_p: 0.9
      repetition_penalty: 1.1
eval:
    - target: evomerge.eval.JaTextExtraction
      params:
        loader_kwargs:
          batch_size: 16  # Increased batch size for smaller model
          num_workers: 2
    - target: evomerge.eval.JaFieldExtraction
      params:
        loader_kwargs:
          batch_size: 16  # Increased batch size for smaller model
          num_workers: 2