model:
  target: evomerge.CausalLM
  params:
    model_path: augmxnt/shisa-gamma-7b-v1
    template: ja-instruct
    model_kwargs:
      torch_dtype: torch.float16
    generation_config:
      max_new_tokens: 1024
      do_sample: false
      temperature: 0.2
      top_p: 0.9
      repetition_penalty: 1.2
eval:
    - target: evomerge.eval.JaTextExtraction
      params:
        loader_kwargs:
          batch_size: 8
          num_workers: 2
    - target: evomerge.eval.JaFieldExtraction
      params:
        loader_kwargs:
          batch_size: 8
          num_workers: 2