from setuptools import setup, find_packages

setup(
    name="bmr-model-merge",
    version="0.1.0",
    description="Japanese invoice/receipt OCR using evolutionary model merging",
    author="Ravikumar Shah",
    author_email="ravikumar.shah@vebuin.com",
    license="Apache 2.0",
    packages=find_packages(),
    install_requires=[
        "transformers>=4.38.2",
        "torch>=2.0.0",
        "vllm>=0.3.0",
        "mergekit=0.0.6",
        "lm-eval>=0.3.0",
        "optuna>=3.3.0",
        "ray>=2.7.0",
        "opencv-python>=4.8.0",
        "pillow>=10.2.0",
        "fasttext>=0.9.2",
        "rouge_score>=0.1.2",
        "fugashi>=1.3.1",
        "emoji>=2.10.1",
        "neologdn>=0.5.2",
        "datasets>=2.18.0",
        "gradio>=4.21.0",
        "accelerate>=0.27.2",
        "unidic-lite>=1.0.8",
        "einops>=0.7.0",
        "sentencepiece>=0.2.0",
        "Levenshtein",
    ],
    python_requires=">=3.10",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
)